
import {
  ArrowRight, ArrowLeft, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Moon, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Trash, User, X, Workflow,
  Bell, FileText, ClipboardCheck, CarFront, Users, CreditCard, BarChart3, ShieldCheck, Filter, FileDown, LogOut, LayoutDashboard, FileSpreadsheet, Building, HandCoins, Route, Briefcase, UserCog, Palette, Languages, KeyRound, BellRing, Eye,
  Repeat,
  ArrowRightLeft,
  ChevronDown as ChevronDownIcon,
  Sparkles,
  CheckCircle,
  XCircle,
  Info,
  MapPin, // Already present for Address Info
  Paperclip, // Added for Documentation
  Lightbulb,
  PhoneForwarded,
  RefreshCw,
  ChevronsLeft,
  ChevronsRight,
  Download,
} from 'lucide-react';

const Icons = {
  download: Download ,
  info: Info,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  chevronDown: ChevronsUpDown,
  chevronSmallDown: ChevronDownIcon,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  dark: Moon,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  settingsUser: UserCog,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  bell: Bell,
  fileText: FileText,
  clipboardCheck: ClipboardCheck,
  carFront: CarFront,
  users: Users,
  creditCard: CreditCard,
  barChart3: BarChart3,
  shieldCheck: ShieldCheck,
  filter: Filter,
  fileDown: FileDown,
  logOut: LogOut,
  dashboard: LayoutDashboard,
  applications: FileText,
  permits: Briefcase,
  reports: FileSpreadsheet,
  vehicleRegistry: CarFront,
  driverDatabase: Users,
  paymentHistory: CreditCard,
  systemAdministration: ShieldCheck,
  userProfile: User,
  notificationPreferences: BellRing,
  systemPreferences: Settings,
  accessControl: Shield,
  passwordChange: KeyRound,
  languageSettings: Languages,
  themeCustomization: Palette,
  emailSettings: Mail,
  handCoins: HandCoins,
  route: Route,
  eye: Eye,
  repeat: Repeat,
  arrowRightLeft: ArrowRightLeft,
  sparkles: Sparkles,
  approveApplication: CheckCircle,
  rejectApplication: XCircle,
  requestMoreInfo: Info,
  viewDocs: FileText,
  routeMap: MapPin, // This was already MapPin, good for consistency
  mapPin: MapPin,   // For Address Info tab
  paperclip: Paperclip, // For Documentation tab
  lightbulb: Lightbulb,
  phoneForwarded: PhoneForwarded,
  refreshCw: RefreshCw,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
};

export {Icons};
